### ISSUE TITLE
Building ignite book code examples for ignite 2

### ISSUE THREAD

**Issue by raviparam** [srecon/ignite-book-code-samples#2]
Hi,
 Can you tell us the changes needed to build this example with ignite  2?. Only changing ignite version in chapters pom.xml is enough?. or any change is required in the code?

**Comment by srecon** [comment]
Hi,
  For most of the examples, changes the version to ignite-2.х is enough. We are working on updates of the samples to version 2, but we do not have any timeline yet.
  Regards 
  Shamim

**Comment by pranasblk** [comment]
How come static code compiles successfully for 2.1 but getting 
```
$ java -jar HelloIgnite-runnable.jar
Hello Ignite
Can't load log handler "org.apache.ignite.logger.java.JavaLoggerFileHandler"
java.lang.ClassNotFoundException: org.apache.ignite.logger.java.JavaLoggerFileHandler
java.lang.ClassNotFoundException: org.apache.ignite.logger.java.JavaLoggerFileHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.util.logging.LogManager$5.run(LogManager.java:965)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
	at java.util.logging.LogManager.access$1500(LogManager.java:145)
	at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
	at java.util.logging.Logger.getHandlers(Logger.java:1777)
	at org.apache.ignite.logger.java.JavaLogger.findHandler(JavaLogger.java:399)
	at org.apache.ignite.logger.java.JavaLogger.configure(JavaLogger.java:229)
	at org.apache.ignite.logger.java.JavaLogger.<init>(JavaLogger.java:170)
	at org.apache.ignite.logger.java.JavaLogger.<init>(JavaLogger.java:126)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.initLogger(IgnitionEx.java:2365)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.initializeConfiguration(IgnitionEx.java:2045)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.start0(IgnitionEx.java:1674)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.start(IgnitionEx.java:1648)
	at org.apache.ignite.internal.IgnitionEx.start0(IgnitionEx.java:1076)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:596)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:520)
	at org.apache.ignite.Ignition.start(Ignition.java:322)
	at com.blu.imdg.HelloIgnite.main(HelloIgnite.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.NoClassDefFoundError: org/h2/result/RowFactory
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at com.simontuffs.onejar.JarClassLoader.defineClass(JarClassLoader.java:803)
	at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:710)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.simontuffs.onejar.JarClassLoader.loadClass(JarClassLoader.java:630)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.ignite.internal.processors.query.h2.IgniteH2Indexing.<clinit>(IgniteH2Indexing.java:197)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.ignite.internal.IgniteComponentType.inClassPath(IgniteComponentType.java:153)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.start0(IgnitionEx.java:1832)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.start(IgnitionEx.java:1648)
	at org.apache.ignite.internal.IgnitionEx.start0(IgnitionEx.java:1076)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:596)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:520)
	at org.apache.ignite.Ignition.start(Ignition.java:322)
	at com.blu.imdg.HelloIgnite.main(HelloIgnite.java:37)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.h2.result.RowFactory
	at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:713)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.simontuffs.onejar.JarClassLoader.loadClass(JarClassLoader.java:630)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more

```

It sounds like 2.1 Apache release is broken, isn't it?

**Comment by srecon** [comment]
No, the Ignite release is Ok. You have to explicitly add the dependency for h2 database as follows:
<dependency>
```
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <version>1.4.195</version>
</dependency>
```
The version 1.4.195 is working for me.
